### ISSUE TITLE
Engine and Fuel Tank 

### ISSUE THREAD

**Issue by WDayneHS** [bentenz5/JackSepticEye-Rocket-Part-Mod-for-KSP#2]
The engine's liquidfuel to oxidizer ratio (0.2 to 0.6) is not the same as the other liquid fuel engines (0.9 to 1.1), and I cannot attach anything to the bottom of the fuel tank.

**Comment by bentenz5** [comment]
Bruh. This is so old. I gave up on this project ages ago.

**Comment by WDayneHS** [comment]
I realize that, sorry for trying to help make something that is absolute better.

**Comment by bentenz5** [comment]
Its alright ;3 I just dont have the time to do as much gaming as I used to ;__;
